Repository userfrosting/UserFrosting, pull requests merged in 2019-09, with the labels that each got.

#1031 Release 4.3.1
  CHANGELOG.md
  app/sprinkles/account/locale/ar/messages.php
  app/sprinkles/account/locale/ar/validate.php
  app/sprinkles/admin/locale/ar/messages.php
  app/sprinkles/admin/schema/requests/user/create.yaml
  app/sprinkles/admin/src/Controller/UserController.php
  app/sprinkles/core/locale/ar/messages.php
  app/sprinkles/core/locale/ar/validate.php
Labels: Release PR

#1033 Fix typos in form.fields.hidden
  app/sprinkles/admin/templates/forms/group.html.twig
Labels: confirmed bug

#1035 Hotfix sr rs
  app/sprinkles/account/locale/sr_RS/messages.php
  app/sprinkles/account/locale/sr_RS/validate.php
  app/sprinkles/admin/locale/sr_RS/messages.php
  app/sprinkles/core/locale/sr_RS/errors.php
  app/sprinkles/core/locale/sr_RS/messages.php
  app/sprinkles/core/locale/sr_RS/validate.php
Labels: internationalization
