Repository userfrosting/UserFrosting, pull requests merged in 2019-06, with the labels that each got.

#996 Updated custom Eloquent relations for Laravel 5.8
  CHANGELOG.md
  README.md
  app/sprinkles/account/src/Database/Migrations/v400/ActivitiesTable.php
  app/sprinkles/account/src/Database/Migrations/v400/GroupsTable.php
  app/sprinkles/account/src/Database/Migrations/v400/PasswordResetsTable.php
  app/sprinkles/account/src/Database/Migrations/v400/PermissionRolesTable.php
  app/sprinkles/account/src/Database/Migrations/v400/PermissionsTable.php
  app/sprinkles/account/src/Database/Migrations/v400/PersistencesTable.php
  app/sprinkles/account/src/Database/Migrations/v400/RoleUsersTable.php
  app/sprinkles/account/src/Database/Migrations/v400/RolesTable.php
  app/sprinkles/account/src/Database/Migrations/v400/UsersTable.php
  app/sprinkles/account/src/Database/Migrations/v400/VerificationsTable.php
  app/sprinkles/account/src/Database/Migrations/v420/AddingForeignKeys.php
  app/sprinkles/account/src/Database/Models/User.php
  app/sprinkles/account/tests/Integration/Controller/AccountControllerTest.php
  app/sprinkles/admin/tests/Integration/Controller/GroupControllerGuestTest.php
  app/sprinkles/admin/tests/Integration/Controller/GroupControllerTest.php
  app/sprinkles/admin/tests/Integration/Controller/PermissionControllerGuestTest.php
  app/sprinkles/admin/tests/Integration/Controller/PermissionControllerTest.php
  app/sprinkles/admin/tests/Integration/Controller/RoleControllerGuestTest.php
  app/sprinkles/admin/tests/Integration/Controller/RoleControllerTest.php
  app/sprinkles/admin/tests/Integration/Controller/UserControllerCreateTest.php
  app/sprinkles/admin/tests/Integration/Controller/UserControllerGuestTest.php
  app/sprinkles/admin/tests/Integration/Controller/UserControllerTest.php
  app/sprinkles/core/composer.json
  app/sprinkles/core/config/default.php
  app/sprinkles/core/src/Bakery/SetupDbCommand.php
  app/sprinkles/core/src/Csrf/SlimCsrfProvider.php
  app/sprinkles/core/src/Database/Migrations/v400/SessionsTable.php
  app/sprinkles/core/src/Database/Models/Concerns/HasRelationships.php
  app/sprinkles/core/src/Database/Relations/BelongsToManyConstrained.php
  app/sprinkles/core/src/Database/Relations/BelongsToManyThrough.php
  app/sprinkles/core/src/Database/Relations/BelongsToManyUnique.php
  app/sprinkles/core/src/Database/Relations/Concerns/Unique.php
  app/sprinkles/core/src/Database/Relations/HasManySyncable.php
  app/sprinkles/core/src/Database/Relations/MorphManySyncable.php
  app/sprinkles/core/src/Database/Relations/MorphToManyUnique.php
  app/sprinkles/core/tests/Integration/Database/DatabaseTests.php
  app/sprinkles/core/tests/Integration/Session/SessionDatabaseHandlerTest.php
  app/sprinkles/core/tests/Integration/Session/SessionFileHandlerTest.php
  app/sprinkles/core/tests/Unit/Database/Relations/BelongsToManyThroughTest.php
  build/before_install.sh
Labels: compatibility

#993 Config settings for password min/max length
  app/sprinkles/account/config/default.php
  app/sprinkles/account/locale/es_ES/messages.php
  app/sprinkles/account/src/Bakery/CreateAdminUser.php
  app/sprinkles/account/src/Controller/AccountController.php
  app/sprinkles/account/templates/forms/settings-account.html.twig
  app/sprinkles/account/templates/pages/register.html.twig
  app/sprinkles/account/templates/pages/reset-password.html.twig
  app/sprinkles/account/templates/pages/set-password.html.twig
  app/sprinkles/admin/src/Controller/RoleController.php
  app/sprinkles/admin/src/Controller/UserController.php
  app/sprinkles/admin/templates/modals/user-set-password.html.twig
Labels: confirmed bug

#987 Resolves Issue #986 - Turn off opportunistic TLS when disabled.
  app/sprinkles/core/config/default.php
  app/sprinkles/core/src/Mail/Mailer.php
Labels: mail, possible bug

#976 Respects CSRF_ENABLED environment variable
  app/sprinkles/core/config/default.php
Labels: confirmed bug
