Repository userfrosting/UserFrosting, pull requests merged in 2019-04, with the labels that each got.

#954 Update Sprunje.php
  app/sprinkles/core/src/Sprunje/Sprunje.php
Labels: confirmed bug, user experience

#969 Hide locale field when only 1 locale is available (#968)
  app/sprinkles/account/src/Controller/AccountController.php
  app/sprinkles/account/templates/forms/settings-profile.html.twig
  app/sprinkles/account/templates/pages/register.html.twig
  app/sprinkles/admin/src/Controller/UserController.php
Labels: internationalization

#958 More helpful error message in checkEnvironment.php
  app/sprinkles/core/src/Util/CheckEnvironment.php
Labels: confirmed bug
