Repository userfrosting/UserFrosting, pull requests merged in 2020-01, with the labels that each got.

#992 Locale:* bakery command
  app/sprinkles/core/src/Bakery/LocaleFixKeysCommand.php
  app/sprinkles/core/src/Bakery/LocaleInfoCommand.php
  app/sprinkles/core/src/Bakery/LocaleMissingKeysCommand.php
  app/sprinkles/core/src/Bakery/LocaleMissingValuesCommand.php
  app/sprinkles/core/src/Util/EnvironmentInfo.php
  app/sprinkles/core/tests/Integration/Bakery/LocaleInfoCommandTest.php
  app/sprinkles/core/tests/Integration/Bakery/LocaleMissingKeysCommandTest.php
  app/sprinkles/core/tests/Integration/Bakery/data/locale/en_US/errors.php
  app/sprinkles/core/tests/Integration/Bakery/data/locale/en_US/foo/bar.php
  app/sprinkles/core/tests/Integration/Bakery/data/locale/en_US/messages.php
  app/sprinkles/core/tests/Integration/Bakery/data/locale/es_ES/errors.php
  app/sprinkles/core/tests/Integration/Bakery/data/locale/es_ES/foo/bar.php
  app/sprinkles/core/tests/Integration/Bakery/data/locale/es_ES/messages.php
  app/sprinkles/core/tests/Integration/Bakery/data/locale/fr_FR/errors.php
  app/sprinkles/core/tests/Integration/Bakery/data/locale/fr_FR/messages.php
  app/system/Bakery/Bakery.php
  app/system/Bakery/BaseCommand.php
  app/tests/TestCase.php
Labels: internationalization

#1057 Use docker-compose extensively and put nodejs available so all commands works ok
  docker-compose.yml
  docker/app/Dockerfile
  docker/app/php/custom.ini
  docker/nginx/default.conf
  docker/php/Dockerfile
Labels: Docker

#1062 Improve ordering by activity date
  app/sprinkles/admin/src/Sprunje/ActivitySprunje.php
Labels: confirmed bug
